# Generated by Django 2.0.3 on 2019-09-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='pubdate',
        ),
    ]
