# Generated by Django 2.0.3 on 2019-09-13 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_songs_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='pubdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
